### PR TITLE
Adding new extension hooks

### PR DESCRIPTION
**Pull request by LightGuard**
There are three new extension hooks in place now:

* before_extensions
+ All extensions added via this method, following the same extension rules,
will be run before any other extensions loaded with `extension`.
* after_extensions
+ All extensions added via this method, following the same extension rules,
will be run after any other extensions loaded with `extension`.
* after_generation
+ All extensions added via this method, following the same extension rules,
will be run after the page generation is completed. This will only run on the 
first generation, not on reloads.

Extensions will now be notified if they are being reloaded. To be notified of
this an extension must have an `on_reload(site)` method, which will be called
if there is a change. An extension is then free to re-run an initialization
logic, clean-up the site variable, or create new state needed for a re-run of
the `execute(site)` method.

### CODE REVIEW

**Comment by LightGuard** [comment]
@aslakknutsen Care to play around with this and see if it will fit your needs?

**Comment by aslakknutsen** [comment]
@LightGuard Will do. before/after sounds nice for a 'load/store cache'

**Comment by aslakknutsen** [comment]
on_reload(site, changed_file) would be useful. Then we know what was updated and can clear disk cache.

**Comment by LightGuard** [comment]
Ah. I was thinking you'd want a notification of the extension being rerun.
What you're talking about is more like reload_page. Also useful I would
think.

On Saturday, April 11, 2015, Aslak Knutsen <notifications@github.com> wrote:

> on_reload(site, changed_file) would be useful. Then we know what was
> updated and can clear disk cache.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/462#issuecomment-91925938>.
>


-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by aslakknutsen** [comment]
@LightGuard technically yes, but.. currently you're just calling on_reload on all extensions. And you don't really know which extension to reload, unless the extension it self, which you don't track, is being reloaded. 

Any way.. the changed file could be a class/file used by an extension. At that point, only the extension it self knows if it needs to redo something based on this change.

**Comment by aslakknutsen** [comment]
The naming is a bit off to me; before_pipeline_extension and after_pipeline_extension

It's part of the pipeline so it's not really before/after _pipeline_ . Maybe just before/after?

**Comment by aslakknutsen** [comment]
perhaps add support for the extension to register these hooks as we do with transformers:
https://github.com/LightGuard/awestruct/blob/feature/add_more_hooks/lib/awestruct/pipeline.rb#L33

```ruby
module TestExtension
   
   class MyBigExtension

      def transform(transformers)
         transformers << MyTrans.new
      end

      def before(befores)
         befores << MyBefore.new
      end

      def after(afters)
         afters << MyAfter.new
      end

      def execute(site)

         # do something

      end
   end

   class MyTrans
      def transform(site, page, rendered)
         wrap_page_with_custom_x(rendered)
      end
   end

   class MyBefore
      def execute(site)
         # site.my_data = load_data()
      end
   end

   class MyAfter
      def execute(site)
         # store_data(my_data)
      end
   end

end


Awestruct::Extensions::Pipeline.new do

   extension TestExtension::MyBigExtension.new

end
```

**Comment by aslakknutsen** [comment]
We do currently workaround this by passing pipeline as an argument, .. which might be just as clean and easier to be honest.. Just the extension registration that looks a bit different from these extensions to the others. e.g.

```ruby
module TestExtension
   
   class MyBigExtension

      def initialize(pipeline)
         pipline.transformer MyTrans.new
         pipline.befores MyBefore.new
         pipline.afters MyAfter.new
      end

      def execute(site)

         # do something

      end
   end

   class MyTrans
      def transform(site, page, rendered)
         wrap_page_with_custom_x(rendered)
      end
   end

   class MyBefore
      def execute(site)
         # site.my_data = load_data()
      end
   end

   class MyAfter
      def execute(site)
         # store_data(my_data)
      end
   end

end


Awestruct::Extensions::Pipeline.new do

   TestExtension::MyBigExtension.new self

end
```

**Comment by LightGuard** [comment]
Well, it actually is run before/after all the extensions, but I couldn't find a good name for it. Do you have any suggestions?

**Pull request merged**
