### PR TITLE
require libraries only when minification is enabled

### PR DESCRIPTION
**Pull request by sridamul**
resolves issue #566

### CODE REVIEW

**Comment by sridamul** [comment]
@zbynek can you review this? And please correct me if I haven't followed the best practices or if the given solution doesn't works as expected

**Comment by zbynek** [comment]
@sridamul how did you come up with `SitePropertyExtractor`? How did you test this?

**Comment by sridamul** [comment]
> @sridamul how did you come up with `SitePropertyExtractor`? How did you test this?

Sorry, I haven't tested and to be fair I don't know how to do it.

**Comment by sridamul** [comment]
Can you help me with this part because I both new to awestruct and ruby

**Comment by sridamul** [comment]
@zbynek Is there any other way to solve this issue?

**Pull request closed without merging**
