### PR TITLE
Close link tags in atom template

### PR DESCRIPTION
**Pull request by rtyler**
Otherwise the generated feed won't actually be valid XML! Eep!

### CODE REVIEW

**Comment by rtyler** [comment]
All of the test failures seem to be in the `Awestruct::Rack::Debug` examples so I'm inclined to believe that this pull requests isn't the root cause of those failures.

Perhaps this is what I get for being the first pull request of the year :)

**Comment by LightGuard** [comment]
The current line three should output xml, This patch shouldn't be needed. Do you have an simple example to demonstrate, or even better a failing test?

**Comment by LightGuard** [comment]
Are we still sure this is needed? I haven't seen a failing test for this yet.

**Comment by rtyler** [comment]
I haven't had a chance to write one, yet. When I upgraded jenkins-infra/jenkins.io to 0.5.7 I did notice the behavior was still the same as far as unclosed tags are concerned though.

**Comment by LightGuard** [comment]
Hm, interesting. No one else has reported this, maybe they're not using an
atom feed :)

On Fri, Mar 11, 2016 at 11:20 AM, R. Tyler Croy <notifications@github.com>
wrote:

> I haven't had a chance to write one, yet. When I upgraded jenkins-infra/
> jenkins.io to 0.5.7 I did notice the behavior was still the same as far
> as unclosed tags are concerned though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/503#issuecomment-195486892>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Pull request closed without merging**
