### PR TITLE
Switching from REXML to Oga

### PR DESCRIPTION
**Pull request by LightGuard**

### CODE REVIEW

**Comment by LightGuard** [comment]
Should fix #446 

@maxandersen @ge0ffrey @xcoulon

**Comment by LightGuard** [comment]
Should also fix #454

**Comment by maxandersen** [comment]
On a quick run on xam.dk it is different, but does not look better.

```
<h1>Unexpected end of input on line 56</h1>
<h2>Rendering file /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml resulted in a failure.</h2>
<p>Line: unknown</p>
<p>Backtrace:</p>
<pre>/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:255:in `parser_error'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:228:in `block in each_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `call'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `add_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:376:in `on_text'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `advance_native'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `block in advance'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:89:in `read_data'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:145:in `advance'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:225:in `each_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/oga.rb:25:in `parse_html'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/context_helper.rb:41:in `fully_qualify_urls'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:41:in `block (2 levels) in singleton class'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:20:in `each'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:20:in `block in singleton class'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:-7:in `instance_eval'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:-7:in `singleton class'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:-9:in `__tilt_70301371466200'
/Users/max/.rvm/gems/ruby-2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
/Users/max/.rvm/gems/ruby-2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
/Users/max/.rvm/gems/ruby-2.2.0/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
/Users/max/.rvm/gems/ruby-2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/page.rb:143:in `rendered_content'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/engine.rb:361:in `generate_page'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/engine.rb:349:in `block in generate_output'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:438:in `call'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:438:in `call_with_index'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:342:in `process_incoming_jobs'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:324:in `block in worker'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:317:in `fork'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:317:in `worker'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:305:in `block in create_workers'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:304:in `each'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:304:in `create_workers'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:263:in `work_in_processes'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:193:in `map'
/Users/max/.rvm/gems/ruby-2.2.0/gems/parallel-1.4.1/lib/parallel.rb:154:in `each'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/engine.rb:346:in `generate_output'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/engine.rb:81:in `run'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/cli/generate.rb:21:in `run'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/cli/invoker.rb:125:in `invoke_generate'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/cli/invoker.rb:49:in `invoke!'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/bin/awestruct:9:in `<top (required)>'
/Users/max/.rvm/gems/ruby-2.2.0/bin/awestruct:23:in `load'
/Users/max/.rvm/gems/ruby-2.2.0/bin/awestruct:23:in `<main>'
/Users/max/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/max/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'</pre>
```

when switching to awestruct 0.5.5 this generates fine (or rather, it survives with "plain old non-perfect html content")

**Comment by maxandersen** [comment]
yeah, so it fails on something as simple as:

```
<body>
<p>Test 
</body>
```

but is okey with

```
<body>
<img src="blah">
test
</body>
```
not sure what logic it follows. img okey, p not ?

**Comment by LightGuard** [comment]
I tested on your site Max, all I had to do was take out the `</embed>` and
it all worked.

On Tue, Apr 7, 2015 at 12:58 AM, Max Rydahl Andersen <
notifications@github.com> wrote:

> yeah, so it fails on something as simple as:
>
> <body>
> <p>Test
> </body>
>
> but is okey with
>
> <body>
> 
> test
> </body>
>
> not sure what logic it follows. img okey, p not ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/460#issuecomment-90405546>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by maxandersen** [comment]
I removed </embed> in all places but its still failing.

can you by any chance submit PR showing the changes you needed  ?

**Comment by maxandersen** [comment]
so with your PR it works.

It is still though much more strict than the old version and the error messaging is not very good since there is no context about which of potentially hundreds of posts is having the error.

i.e. I got this for one of my files:

```
<h1>Unexpected text, expected attribute instead on line 10</h1>
<h2>Rendering file /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml resulted in a failure.</h2>
<p>Line: unknown</p>
<p>Backtrace:</p>
<pre>/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:255:in `parser_error'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:228:in `block in each_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `call'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `add_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:376:in `on_text'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `advance_native'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `block in advance'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:89:in `read_data'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:145:in `advance'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:225:in `each_token'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/oga.rb:25:in `parse_html'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/context_helper.rb:41:in `fully_qualify_urls'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:41:in `block (2 levels) in singleton class'
/Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:20:in `each'
```
I don't know how to fix this since it is happening in a haml file for which there seem to be no way of propagating out which context an exception is occuring in ;/

But at least oga is better than what is in master now, but not as forgiven nor informative as 0.5.5.

**Comment by LightGuard** [comment]
Is that the full stack trace? We can probably figure it out how to make it
more helpful, but there should be more to the stack trace.

On Wed, Apr 8, 2015 at 1:03 AM, Max Rydahl Andersen <
notifications@github.com> wrote:

> so with your PR it works.
>
> It is still though much more strict than the old version and the error
> messaging is not very good since there is no context about which of
> potentially hundreds of posts is having the error.
>
> i.e. I got this for one of my files:
>
> <h1>Unexpected text, expected attribute instead on line 10</h1>
> <h2>Rendering file /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml resulted in a failure.</h2>
> <p>Line: unknown</p>
> <p>Backtrace:</p>
> <pre>/Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:255:in `parser_error'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:228:in `block in each_token'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `call'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:179:in `add_token'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:376:in `on_text'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `advance_native'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:146:in `block in advance'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:89:in `read_data'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/lexer.rb:145:in `advance'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:225:in `each_token'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/xml/parser.rb:262:in `parse'
> /Users/max/.rvm/gems/ruby-2.2.0/gems/oga-0.3.0/lib/oga/oga.rb:25:in `parse_html'
> /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/context_helper.rb:41:in `fully_qualify_urls'
> /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:41:in `block (2 levels) in singleton class'
> /Users/max/.rvm/gems/ruby-2.2.0/bundler/gems/awestruct-9e5e1b6bcfd8/lib/awestruct/extensions/template.atom.haml:20:in `each'
>
> I don't know how to fix this since it is happening in a haml file for
> which there seem to be no way of propagating out which context an exception
> is occuring in ;/
>
> But at least oga is better than what is in master now, but not as forgiven
> nor informative as 0.5.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/460#issuecomment-90824835>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
I'll merge, but could you create an issue to help us get better error reporting for this?

**Comment by maxandersen** [comment]
The full stack trace is in https://github.com/awestruct/awestruct/pull/460#issuecomment-90400214 but i'll open bug too.

**Pull request merged**
