### PR TITLE
Using threads instead of processes for build

### PR DESCRIPTION
**Pull request by LightGuard**
Yes, this is a little bit slower, but we can actually catch errors and exit correctly now.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
On RMI that essentially means run single threaded, as it has no real threads. Works on JRuby tho.

**Comment by LightGuard** [comment]
Yeah, I know, but unless you can find a good way of doing this in different
processes and capture failures in those processes during generation, this
is the best we have.

On Mon, Apr 6, 2015 at 2:43 PM, Aslak Knutsen <notifications@github.com>
wrote:

> On RMI that essentially means run single threaded, as it has no real
> threads. Works on JRuby tho.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/459#issuecomment-90233595>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by aslakknutsen** [comment]
```ruby
errors = Parallel.each(@site.pages, :in_processes => Parallel.processor_count) do |page|
   begin
      do_stuff
   rescue => e
      return e
   end
end

errors = errors.select {|e| !e.nil?}
```

?

**Comment by LightGuard** [comment]
That works? All the other processes pick up and continue with the extra
work from the now dead process?

On Tue, Apr 7, 2015 at 12:28 AM, Aslak Knutsen <notifications@github.com>
wrote:

> errors = Parallel.each(@site.pages, :in_processes => Parallel.processor_count) do |page|
>    begin
>       do_stuff
>    rescue => e
>       return e
>    endend
>
> errors = errors.select {|e| !e.nil?}
>
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/pull/459#issuecomment-90392385>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by aslakknutsen** [comment]
To my knowledge.. The so called dead process return a controlled error, the mother process reports that. 

If the child process die of other reasons Parallel should have some kinda timeout to kill it. Not sure if it does, but it should..

**Pull request merged**
